version: '3'

services:
  ftp_server:
    image: garethflowers/ftp-server
    container_name: test-ftp-server
    environment:
      - FTP_PASS=admin
      - FTP_USER=admin
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - "C:/Users/marco/Documents/FtpServerFiles:/home/admin"
    restart: always