//
// Created by marco on 27/02/2024.
//

#ifndef FTP_CLIENT_FTPSERVERRESPONSECODE_H
#define FTP_CLIENT_FTPSERVERRESPONSECODE_H

enum FtpServerResponseCode : int16_t {
    // Positive Preliminary replies
    SERVICE_READY_IN_NNN_MINUTES = 120,
    DATA_CONNECTION_ALREADY_OPEN = 125,
    FILE_STATUS_OKAY = 150,

    // Positive Completion replies
    COMMAND_OKAY = 200,
    COMMAND_NOT_IMPLEMENTED_SUPERFLUOUS_AT_THIS_SITE = 202,
    SYSTEM_STATUS_OR_HELP_REPLY = 211,
    DIRECTORY_STATUS = 212,
    FILE_STATUS = 213,
    HELP_MESSAGE = 214,
    SYSTEM_TYPE = 215,
    SERVICE_READY_FOR_NEW_USER = 220,
    SERVICE_CLOSING_CONTROL_CONNECTION = 221,
    DATA_CONNECTION_OPEN = 225,
    CLOSING_DATA_CONNECTION = 226,
    ENTERING_PASSIVE_MODE = 227,
    USER_LOGGED_IN = 230,
    REQUESTED_FILE_ACTION_OKAY = 250,
    PATHNAME_CREATED = 257,

    // Positive Intermediate replies
    USER_NAME_OKAY_NEED_PASSWORD = 331,
    NEED_ACCOUNT_FOR_LOGIN = 332,
    REQUESTED_FILE_ACTION_PENDING_FURTHER_INFORMATION = 350,

    // Transient Negative Completion replies
    SERVICE_NOT_AVAILABLE = 421,
    CANNOT_OPEN_DATA_CONNECTION = 425,
    CONNECTION_CLOSED_TRANSFER_ABORTED = 426,
    FILE_BUSY = 450,
    LOCAL_ERROR_IN_PROCESSING = 451,
    INSUFFICIENT_STORAGE_SPACE = 452,

    // Permanent Negative Completion replies
    COMMAND_NOT_IMPLEMENTED = 502,
    BAD_SEQUENCE_OF_COMMANDS = 503,
    COMMAND_NOT_IMPLEMENTED_FOR_THAT_PARAMETER = 504,
    NOT_LOGGED_IN = 530,
    NEED_ACCOUNT_FOR_STORING_FILES = 532,
    FILE_NOT_FOUND = 550,
    PAGE_TYPE_UNKNOWN = 551,
    EXCEEDED_STORAGE_ALLOCATION = 552,
    FILE_NAME_NOT_ALLOWED = 553
};

#endif //FTP_CLIENT_FTPSERVERRESPONSECODE_H
